
#数据源配置
spring:
  application:
    name: mobile-service

  datasource:
    url: jdbc:mysql://rm-2ze1oiwuqgur01f4q.mysql.rds.aliyuncs.com/enterprise
    username: zhaobangshou
    password: 123qweQWE
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: enterprise-pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

  redis:
        #数据库索引
        database: 0
        host: 127.0.0.1
        port: 6379
        password: admin123
        jedis:
          pool:
            #最大连接数
            max-active: 8
            #最大阻塞等待时间(负数表示没限制)
            max-wait: -1
            #最大空闲
            max-idle: 8
            #最小空闲
            min-idle: 0
        #连接超时时间
        timeout: 10000
  mail:
      default-encoding: UTF-8
      host: smtp.163.com
      port: 465
      username: zhaobangshou2019@163.com
      password: zhaobangshou2019
      test-connection: false
      properties:
              mail:
                  smtp:
                    auth: true
                    starttls:
                        enable: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-6
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 10002
  max-http-header-size: 102400000
  jetty:
    max-http-post-size: 102400000
  tomcat:
    basedir: /home/logs
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  path: /home/logs/


file:
  path: /home/data/

admin:
  email: ruiliqiji2019@126.com